defaults:
  endpoint: /fibo/webapi
  password: "12345678"
  apn: oai
  profile_name: oai
  pdp_type: 0
  set_default: true

dongles:
  - ip: 192.168.101.1
    endpoint: /thru/webapi
    password: "12345678"
  - ip: 192.168.102.1
    endpoint: /fibo/webapi
    password: "12345678"
  - ip: 192.168.103.1
    endpoint: /thru/webapi
    password: "12345678"
  - ip: 192.168.104.1
    endpoint: /fibo/webapi
    password: "12345678"
  - ip: 192.168.105.1
    endpoint: /thru/webapi
    password: "12345678"
