Active_gNBs:
  - gnb-cucp-rfsim
Asn1_verbosity: none

gNBs:
  - gNB_ID: 0xe00
    gNB_name: gnb-cucp-rfsim
    tracking_area_code: 81
    plmn_list:
      - mcc: 001
        mnc: 01
        mnc_length: 2
        snssaiList:
          - sst: 1
            sd: 0xffffff
          - sst: 1
            sd: 0x01
          - sst: 1
            sd: 0x02
          - sst: 1
            sd: 0x03
          - sst: 1
            sd: 0x04
          - sst: 1
            sd: 0x05
    nr_cellid: 12345678
    tr_s_preference: f1
    local_s_address: 192.168.202.141
    remote_s_address: 192.168.202.140
    local_s_portd: 2153
    remote_s_portd: 2153
    SCTP:
      SCTP_INSTREAMS: 2
      SCTP_OUTSTREAMS: 2
    amf_ip_address:
      - ipv4: 10.53.1.2
    E1_INTERFACE:
      - type: cp
        ipv4_cucp: 192.168.202.141
        port_cucp: 38462
        ipv4_cuup: 192.168.202.142
        port_cuup: 38462
    NETWORK_INTERFACES:
      GNB_IPV4_ADDRESS_FOR_NG_AMF: 10.53.1.141

security:
  ciphering_algorithms: [nea0]
  integrity_algorithms: [nia2, nia0]
  drb_ciphering: yes
  drb_integrity: no

log_config:
  global_log_level: info
  pdcp_log_level: info
  rrc_log_level: info
  ngap_log_level: debug
  f1ap_log_level: debug

e2_agent:
  near_ric_ip_addr: 192.168.201.142
  sm_dir: /usr/local/lib/flexric/
