Active_gNBs:
  - gnb-cuup1-rfsim
Asn1_verbosity: none

gNBs:
  - gNB_ID: 0xe00
    gNB_CU_UP_ID: 0xe00
    gNB_name: gnb-cuup1-rfsim
    tracking_area_code: 81
    plmn_list:
      - mcc: 001
        mnc: 01
        mnc_length: 2
        snssaiList:
          - sst: 1
            sd: 0x01
    nr_cellid: 12345678
    tr_s_preference: f1
    local_s_address: 192.168.202.143
    remote_s_address: 192.168.202.140
    local_s_portd: 2153
    remote_s_portd: 2153
    SCTP:
      SCTP_INSTREAMS: 2
      SCTP_OUTSTREAMS: 2
    E1_INTERFACE:
      - type: up
        ipv4_cucp: 192.168.202.141
        ipv4_cuup: 192.168.202.143
    NETWORK_INTERFACES:
      GNB_IPV4_ADDRESS_FOR_NG_AMF: 10.53.1.143
      GNB_IPV4_ADDRESS_FOR_NGU: 10.53.1.143
      GNB_PORT_FOR_S1U: 2152

security:
  ciphering_algorithms: [nea0]
  integrity_algorithms: [nia2, nia0]
  drb_ciphering: yes
  drb_integrity: no

log_config:
  global_log_level: info
  pdcp_log_level: info
